[package]
name = "rust_stats"
version = "0.1.0"
edition = "2021"
authors = ["Gary Boone <gary.boone@gmail.com>"]
license = "MIT"
include = ["src/**/*", "LICENSE", "README.md"]

[dependencies]
approx = "0.5.1"
